"""Added new model

Revision ID: 0a9e518fcc5c
Revises: da192b6f3569
Create Date: 2024-01-11 01:32:31.856497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9e518fcc5c'
down_revision = 'da192b6f3569'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
