"""Added model

Revision ID: 172a460d668c
Revises: 49310af0c02e
Create Date: 2024-01-11 01:31:58.241910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172a460d668c'
down_revision = '49310af0c02e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
